### ISSUE TITLE
Components.json

### ISSUE THREAD

**Issue by Cmosley** [kiliman/epic-stack-theme#1]
Shouldn't the css property in the components.json file point to app/styles/tailwind.css ? There is no global.css in your repo. 

Otherwise, excellent example, working on integrating shadcn into my epic stack app today.

**Comment by kiliman** [comment]
Probably. I think Kent must have renamed the CSS file after setting it up, as the file is named `app/styles/tailwind.css`. 

I'm not sure if the `shadcn/ui` CLI updates the CSS file after the initial import, so probably doesn't matter what is in `components.json`. But generally you'd want to keep those in sync.
